import { sql } from '@/lib/db'
import type { EnqueueOptions, Job, JobStats from './types'

let schemaEnsured = false

export async function ensureSchema(): Promise<void> {
  if (schemaEnsured) return
  await sql`\n    CREATE TABLE IF NOT EXISTS background_jobs (\n      id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n      type TEXT NOT NULL,\n      payload JSONB NOT NULL DEFAULT '{}'::jsonb,\n      status TEXT NOT NULL DEFAULT 'queued',\n      attempts INTEGER NOT NULL DEFAULT 0,\n      max_attempts INTEGER NOT NULL DEFAULT 5,\n      last_error TEXT,\n      last_error_at TIMESTAMPZ,\n      next_attempt_at TIMESTAMPZ NOT NULL DEFAULT now(),\n      dedupe_key TEXT UNIQUE,\n      created_at TIMESTAMPZ NOT NULL DEFAULT now(),\n      updated_at TIMESTAMPZ NOT NULL DEFAULT now()\n    )\n  `\n  schemaEnsured = true\n}

export class BackgroundQueue {\n  async enqueue<T>(type: string, payload: T, options: EnqueueOptions = {}): Promise<string> {
    await ensureSchema()
    const { dedupeKey, maxAttempts = 5, runAt } = options
    const nextAttemptAt = runAt ?? new Date()

    if (dedupeKey) {
      const existing = await sql`\n        SELECT id FROM background_jobs WHERE dedupe_key = ${dedupeKey}\n      `\n      if (existing.length > 0) return existing[0].id\n    }\n\n    const result = await sql`\n      INSERT INTO background_jobs (type, payload, max_attempts, next_attempt_at, dedupe_key)\n      VALUES (${type}, ${JSON.stringify(payload)}, ${maxAttempts}, ${nextAttemptAt.toISOString()}, ${dedupeKey ?? null})\n      ON CONFLICT (dedupe_key) NOT NOTHING\n      RETURNING id\n    `\n    if (result.length > 0) return result[0].id\n\n    const existing = await sql`\n      SELECT id FROM background_jobs WHERE dedupe_key = ${dedupeKey}\n    `\n    return existing[0].id\n  }\n\n  async getJob(id: string): Promise<Job | null> {\n    await ensureSchema()\n    const rows = await sql`\n      SELECT id, type, payload, status, attempts, max_attempts, last_error, last_error_at, next_attempt_at, created_at, updated_at\n      FROM background_jobs WHERE id = ${id}\n    `\n    return rows.length ? mapRow(rows[0]) : null\n  }\n\n  async listJobs(limit = 50): Promise<Job[]> {\n    await ensureSchema()\n    const rows = await sql`\n      SELECT id, type, payload, status, attempts, max_attempts, last_error, last_error_at, next_attempt_at, created_at, updated_at\n      FROM background_jobs\n      ORDER BY created_at DESC\n      LIMIT ${limit}\n    `\n    return rows.map(mapRow)\n  }\n\n  async getStats(): Promise<JobStats> {\n    await ensureSchema()\n    const rows = await sql`\n      SELECT status, COUNT(*)::int AS count FROM background_jobs GROUP BY status\n    `\n    const stats: JobStats = { queued: 0, processing: 0, completed: 0, failed: 0 }\n    for (const row of rows) {\n      if (row.status in stats) {\n        stats[row.status as keyof JobStats] = row.count\n      }\n    }\n    return stats\n  }\n}\n\nexport function mapRow(row: any): Job {\n  return {\n    id: row.id,\n    type: row.type,\n    payload: row.payload,\n    status: row.status,\n    attempts: row.attempts,\n    maxAttempts: row.max_attempts,\n    lastError: row.last_error,\n    lastErrorAt: row.last_error_at,\n    nextAttemptAt: row.next_attempt_at,\n    createdAt: row.created_at,\n    updatedAt: row.updated_at,\n  }\n}\n\nexport const queue = new BackgroundQueue()\nexport default queue\n